
version: "3"
services:
  mysql-standalone-image:
    image: "mysql:5.7"
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: UpthGhcZeIwS213yog12
      MYSQL_PASSWORD: UpthGhcZeIwS213yog12
      MYSQL_DATABASE: bl4eo7igdj30wlaukfkb
    ports:
      - "3307:3306"
  springboot-docker-image:
    image: springboot-docker-container
    container_name: springboot-container
    ports:
      - "80:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://uarncvbglma6d2wh:UpthGhcZeIwS213yog12@bl4eo7igdj30wlaukfkb-mysql.services.clever-cloud.com:20140/bl4eo7igdj30wlaukfkb
      SPRING_DATASOURCE_USERNAME: "uarncvbglma6d2wh"
      SPRING_DATASOURCE_PASSWORD: "UpthGhcZeIwS213yog12"
    build:
      context: "./"
      dockerfile: "Dockerfile"
    depends_on:
      - mysql-standalone-image